Import('env')

env['CPPPATH'] = [
    '#include',
]

env['LIBPATH'] = [
    '../components/unixkit/lib',
]

env['LIBS'] = [
    'unixkit',
    'pthread',
]

env.ParseConfig(env['CONFIG_PARSER'])

env.Program('test_daemon', [ 'test_daemon.c' ])
env.Program('test_filewriter', [ 'test_filewriter.c' ])
env.Program('test_fork', [ 'test_fork.c' ])
env.Program('test_get_fd_path', [ 'test_get_fd_path.c' ])
env.Program('test_get_peer_credentials', [ 'test_get_peer_credentials.c' ])
env.Program('test_path', [ 'test_path.c' ])
env.Program('test_rename', [ 'test_rename.c' ])
env.Program('test_renameat', [ 'test_renameat.c' ])
env.Program('test_unix_listen', [ 'test_unix_listen.c' ])
