Import('env')

import os

include = env.Install('include/unixkit', ['#include/unixkit.h'])
lib = env.Install('lib', ['../../src/libunixkit.a'])

env.Alias(
    'install',
    env.Install(os.path.join(env['PREFIX'], 'include/unixkit'), include),
)
env.Alias('install', env.Install(os.path.join(env['PREFIX'], 'lib'), lib))

env['CONFIG_BUILDER'](env)
